/**
 * Photos/videos generated by `yarn media` (see scripts/media.mjs). Every
 * src/data/media/<trip>.json manifest is picked up automatically — no
 * imports to add when a new trip gets media.
 */
export interface MediaItem {
  id: string;
  type: "image" | "video";
  /** grid-sized image, or the web-encoded video */
  src: string;
  /** lightbox-sized image (images only) */
  full?: string;
  /** still frame shown before a video plays (videos only) */
  poster?: string;
  /** small cropped preview (map markers, place panels) */
  thumb?: string;
  width: number;
  height: number;
  /** seconds (videos only) */
  duration?: number;
  /** local wall-clock capture time at the destination, "2026-01-16T13:08:36" */
  takenAt: string;
  /** the file's own timestamp was unreliable (re-saved copy); takenAt is estimated — trust the day, not the time */
  dateEstimated?: boolean;
  /** from src/data/places/<trip>.json — "Fushimi Inari" (absent when only the city is known) */
  place?: string;
  /** the place's name in the local script, "伏見稲荷大社" */
  placeJa?: string;
  city?: string;
  cityJa?: string;
  lat?: number;
  lon?: number;
  /** true: the photo's own GPS; false: the place's position (the photo itself had none) */
  exact?: boolean;
}

/** A name with its optional local-script form: { en: "Kyoto", ja: "京都" } */
export interface Named {
  en: string;
  ja?: string;
}

/** "Fushimi Inari, Kyoto" / "Kyoto" / "" */
export function placeLabel(item: MediaItem) {
  return [item.place, item.city].filter(Boolean).join(", ");
}

/** The most specific local-script name: the place's, else the city's. */
export function localLabel(item: MediaItem) {
  return item.place ? item.placeJa : item.cityJa;
}

/** Distinct names in first-seen order, e.g. the places visited in a day. */
function inOrder(names: (Named | undefined)[]) {
  const seen = new Map<string, Named>();
  for (const n of names) if (n && !seen.has(n.en)) seen.set(n.en, n);
  return [...seen.values()];
}

const cityOf = (i: MediaItem): Named | undefined => (i.city ? { en: i.city, ja: i.cityJa } : undefined);
const placeOf = (i: MediaItem): Named | undefined => (i.place ? { en: i.place, ja: i.placeJa } : undefined);

export function dayCities(items: MediaItem[]) {
  return inOrder(items.map(cityOf));
}

export function dayPlaces(items: MediaItem[]) {
  return inOrder(items.map(placeOf));
}

/** Cities in travel order, collapsing consecutive repeats: Tokyo → Kamakura → Kyoto → … */
export function route(items: MediaItem[]) {
  const stops: Named[] = [];
  for (const item of items) {
    const city = cityOf(item);
    if (city && stops.at(-1)?.en !== city.en) stops.push(city);
  }
  return stops;
}

export interface MediaDay {
  /** "2026-01-16" */
  date: string;
  items: MediaItem[];
}

const manifests = import.meta.glob<{ trip: string; items: MediaItem[] }>("./media/*.json", {
  eager: true,
  import: "default",
});

const byTrip: Record<string, MediaItem[]> = Object.fromEntries(
  Object.values(manifests).map((m) => [m.trip, m.items]),
);

export function getTripMedia(slug: string): MediaItem[] {
  return byTrip[slug] ?? [];
}

/**
 * The trip day a capture belongs to. Days roll over at 4am rather than
 * midnight, so a 00:30 dinner stays with the evening it was part of.
 */
export function tripDay(takenAt: string) {
  return new Date(Date.parse(`${takenAt}Z`) - 4 * 3_600_000).toISOString().slice(0, 10);
}

/** Items are already sorted by capture time; this just splits them at each new trip day. */
export function groupByDay(items: MediaItem[]): MediaDay[] {
  const days: MediaDay[] = [];
  for (const item of items) {
    const date = tripDay(item.takenAt);
    const last = days[days.length - 1];
    if (last?.date === date) last.items.push(item);
    else days.push({ date, items: [item] });
  }
  return days;
}

// takenAt is already local time, so format it as-is (UTC in, UTC out) —
// never let the viewer's own timezone shift the date.
const dayFormat = new Intl.DateTimeFormat("en-US", { month: "short", day: "2-digit", timeZone: "UTC" });
const timeFormat = new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" });

/** "2026-01-16" → "Jan 16" */
export function formatDay(date: string) {
  return dayFormat.format(new Date(`${date}T00:00:00Z`));
}

/** "Jan 16 · 13:08" — just "Jan 16" when the time was only estimated */
export function formatTakenAt(item: Pick<MediaItem, "takenAt" | "dateEstimated">) {
  const d = new Date(`${item.takenAt}Z`);
  return item.dateEstimated ? dayFormat.format(d) : `${dayFormat.format(d)} · ${timeFormat.format(d)}`;
}

/** 7.8 → "0:08" */
export function formatDuration(seconds = 0) {
  const s = Math.round(seconds);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
}
